### ISSUE TITLE
build_ME_model.ipynb PFL reaction change

### ISSUE THREAD

**Issue by h8dinh** [SBRG/ecolime#10]
At build_ME_model.ipynb, part 8, corrections, changing PFL info (#this reaction was edited based on iJO1366 GPR) does not update me.stoichiometric_data.PFL.parent_reactions. This causes error when trying to knockout PFL metabolic reactions using parent_reactions call.

**Comment by h8dinh** [comment]
Suggest hot fix in /ecolime/ecolime/build_ME_model.ipynb:
Part 1-6 (cell #8): add the following lines to remove PFL_FWD_EG11910-MONOMER_dimer to prevent PFL.parent_reactions calling issue:
rxn_to_cplx_dict['PFL'] = {'KETOBUTFORMLY-INACT-MONOMER', 'PYRUVFORMLY-INACTIVE-CPLX',
                           'PYRUVFORMLY-MONOMER_EG11784-MONOMER'}

Part 8 - Corrections (cell #30): remove the following line:
me.reactions.get_by_id('PFL_FWD_EG11910-MONOMER_dimer').remove_from_model()

**Comment by coltonlloyd** [comment]
Thanks for pointing this out @h8dinh. I'll incorporate this into the next push
