### ISSUE TITLE
biomass_allocation piechart key errors

### ISSUE THREAD

**Issue by emarquez0** [SBRG/ecolime#15]
Hi, I've been trying to use the make_composition_piechart from the ecolime/ecolime/characterization/biomass_allocation.py scrip but I keep geting a _KeyError: 'SA_demand_Inner_Membrane'_ and I was hoping that you could help me figure out why.

This key isn't in my x_dict nor any of the "SA_demand". To make my model I used the build_ME_model.ipynb script.

Do I need to use another script before the _make_composition_piechart_ function?

Thank you.

**Comment by emarquez0** [comment]
Also, when I use the function with make_composition_piechart with kind == 'Biomass', it pops out _TypeError: get_biomass_composition() missing 1 required positional argument: 'model'_  so I had to add the argument model=model in line 142 _get_biomass_composition(**model=model**,solution=solution)_

Thanks

**Comment by coltonlloyd** [comment]
Hi,
Thanks for pointing out this bug. I just pushed commit that should have corrected it (efd27a5). 

Let me know if you run into any other problems!
