### ISSUE TITLE
biomass_allocation.py get_by_id problem

### ISSUE THREAD

**Issue by emarquez0** [SBRG/ecolime#16]
Hi!  I tried to use the get_protein_distribution from the ecolime/ecolime/characterization/biomass_allocation.py scrip but I get the next error:

**AttributeError: 'generator' object has no attribute 'get_by_id'**

from the line 

**--> 185             protein_mass = model.translation_data.get_by_id(protein).mass**

Thank you!

**Comment by emarquez0** [comment]
Also, with the rna_to_protein_ratio it says that 

**~/ME_model/Ecolime/ecolime/characterization/biomass_allocation.py in rna_to_protein_ratio(model, solution)
     58                       composition['rRNA'] + composition['ncRNA']) / \
     59                      (composition['Protein'] +
---> 60                       composition['Unmodeled Protein'])
     61     return rna_to_protein
     62 

ZeroDivisionError: float division by zero**

I believe it is because "Protein" is now  "protein" and "Unmodeled Protein" doesn't longer exist

**Comment by coltonlloyd** [comment]
Hi,

Sorry about that. This module isn't tested as well as it should be. I just pushed some changes in 3bb9e62 that should correct these issues.

Thanks for letting me know about this and let me know if you run into any other issues!

Colton
