### ISSUE TITLE
ME model can change the objective function?

### ISSUE THREAD

**Issue by maozhitao** [SBRG/ecolime#17]
When solving the model, the objective function is to maximize the dummy-protein(CPLX-dummy). Can we change the objective function, such as setting the maximum acetate production? Is it possible to achieve functions like optknock, maximizing the target product with maximized biomass?

**Comment by coltonlloyd** [comment]
Yes you can, you just need to set the objective of the dummy reaction to 0 and the objective of acetate production to 1. This can be done with the following:

`me.reactions.dummy_reaction_FWD_SPONT.objective_coefficient = 0 me.reactions.EX_ac_e.objective_coefficient = 1`

Though at the maximum optimal growth rates (when the solve precision is <= 1e-6) there is practically only one unique flux solution. This means that the dummy_reaction_FWD_SPONT flux will always be effectively 0 and the EX_ac_e flux will be identical it's value when the EX_ac_e is not optimized.

At suboptimal growth rates, however, the reactions that are optimized will affect the flux solution.

**Comment by maozhitao** [comment]
Thank you very much！I'll try it.
