### ISSUE TITLE
EG10544-MONOMER_mod_palmitate

### ISSUE THREAD

**Issue by laurenceyang33** [SBRG/ecolime#2]
EG10544-MONOMER_mod_palmitate cannot be made?

for rxn in me.metabolites.get_by_id('EG10544-MONOMER_mod_palmitate').reactions:
    print rxn.id, ':', rxn.reaction
    print

ALPATG160pp1_FWD_EG10168-MONOMER : pg160_p + EG10544-MONOMER_mod_palmitate + 6.3610692415329e-6*mu EG10168-MONOMER --> 2agpg160_p + EG10544-MONOMER

ALPATE160pp1_FWD_EG10168-MONOMER : EG10544-MONOMER_mod_palmitate + 6.3610692415329e-6*mu EG10168-MONOMER + pe160_p --> 2agpe160_p + EG10544-MONOMER

**Comment by coltonlloyd** [comment]
EG10544-MONOMER_mod_palmitate activity was replaced by a more thorough lpp/lipoprotein modification network from iJL1678-ME
